// 🔑 Insert your API keys here
window.CONFIG = {
  SHYFT_API_KEY: "VzPp9y_hw4dFfmfF"
  SOLSCAN_API_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOjE3NTY4MjEzODc3MzIsImVtYWlsIjoidHVyYm90dWdhdHVnYUBnbWFpbC5jb20iLCJhY3Rpb24iOiJ0b2tlbi1hcGkiLCJhcGlWZXJzaW9uIjoidjIiLCJpYXQiOjE3NTY4MjEzODd9.S9IYCLlEUw4dBFhIPjKgq_yLrVOe6EVbkfHI3c4Lv50
"
};
